nome = input('Escreva seu nome completo: ')
idade = input('Insira sua idade: ')
altura = input('Insira sua altura: ')
cpf = input('Insira seu cpf: ')
endereco = input('Insira seu endereço: ')
telefone = input('Insira seu telefone: ')

print('Nome:', nome)
print('Idade:', idade)
print('Altura:', altura)
print('CPF:', cpf)
print('Endereço:', endereco)
print('Telefone:', telefone)
